# Generated by Django 4.1.7 on 2023-02-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='patient_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'department': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
